Mark / install config.json
CARTAvis/carta-archived pull request #57
Opened 2017-04-07 01:41 UTC by markccchiang

I modify the file "carta/carta.pro", add two files "carta/config/config.json" and "carta/config/config.pro" in this branch. So the main configuration file will automatically install in the Carta build directory as the default set.

2017-04-10 03:49 UTC, grimmer0125 commented on carta/carta.pro
> +# SUBDIRS += scriptedClient
Commenting these two lines means they did not do anything before?

2017-04-10 03:54 UTC, markccchiang commented
Yes, I think so.

2017-04-10 11:49 GMT+08:00 Grimmer <notifications@github.com>:

> *@grimmer0125* commented on this pull request.
> ------------------------------
>
> In carta/carta.pro
> <https://github.com/CARTAvis/carta/pull/57#discussion_r110567847>:
>
> > @@ -14,12 +14,12 @@ dbg( "===---------------------------------------------====")
>
>  TEMPLATE = subdirs
>  SUBDIRS += cpp
> -SUBDIRS += scriptedClient
> -SUBDIRS += scripts
> +SUBDIRS += config
> +# SUBDIRS += scriptedClient
>
> Commenting these two lines means they did not do anything before?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CARTAvis/carta/pull/57#pullrequestreview-31749695>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFIWEoRqn2_hUfMub6E-WjodX60AVUjbks5ruabSgaJpZM4M2XM8>
> .
>

2017-04-11 07:52 UTC, grimmer0125 commented
@markccchiang , @ajm-asiaa 
When releasing, "qtDecorations" should be  "false".

How to tell it is building in release mode:
1. CARTA_BUILD_TYPE = release

2017-04-13 04:39 UTC, ajm-asiaa commented
I'm not sure if this is working, at least when compiling the old way. 
I seem to end up with a file called "empty.lprof" of 0 bytes in the "~/cartabuild/build/cpp/desktop/desktop.app/Contents/Resources/ folder"

Do you have that Mark?

Of course I know I could manually copy the config.json there from ~/cartabuild/build/config/ as an extra step.

2017-04-13 04:55 UTC, ajm-asiaa commented
Oh I see. An old version of the code also has a "empty.lprof" file in the desktop.app/Contents/Resources/ folder.

So I guess we do need a post build step to copy the config.json into there?

I see there is a difference in the contents of the build folder for this commit and an older version of the source code:
This commit: /build contains Makefile config/ cpp/
Older version: /build contains Makefile cpp/ scriptedClient/ scripts/

2017-04-13 05:24 UTC, ajm-asiaa commented
One more question Mark.
Which carta.sh script do you use?

2017-04-13 05:40 UTC, markccchiang commented
Hi Anthony,

We don't need to copy config.json to the directory
CARTAVis/build/config/config.json. "qmake" will do this step automatically,
since I have modified the file CARTAVis/carta/carta.pro in this branch.
BTW, the carta.sh script I used is the same with develop branch.

2017-04-13 13:24 GMT+08:00 Anthony Moraghan <notifications@github.com>:

> One more question Mark.
> Which carta.sh script do you use?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CARTAvis/carta/pull/57#issuecomment-293784950>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AFIWEk85E3NZuNjxiOglBrdhTS2_SKx7ks5rvbGQgaJpZM4M2XM8>
> .
>

2017-04-13 05:44 UTC, ajm-ska reviewed
test3

2017-04-13 05:44 UTC, ajm-asiaa commented on carta/carta.pro
>  CONFIG(debug,debug|release) {
test

2017-04-13 05:44 UTC, ajm-asiaa commented on carta/config/config.json
> +    "qtDecorations" : "true"
tedst2

2017-04-13 06:00 UTC, ajm-asiaa commented
Thanks Mark. It seems to me that when we run "carta.sh", if ~/.cartavis/config.json is not present, then it will run setupcartavis.sh which will copy it there.

/CARTAvis/carta/scripts/legacy/carta.sh:
```
if [ ! -d $HOME/CARTA/Images/CubesTest -o\
     ! -d $HOME/.cartavis/log  -o\
     ! -f $HOME/.cartavis/config.json -o\
     ! -d $HOME/CARTA/snapshots/data ]; then
    $dirname/setupcartavis.sh 2>&1  > /dev/null
fi
```

/CARTAvis/carta/scripts/setupcartavis.sh
```
# check that config.json exists
if [ ! -f $HOME/.cartavis/config.json ]; then
    echo "copying config.json file to  $HOME/.cartavis directory..."
    cp $dirname/config/config.json $HOME/.cartavis
fi
```

Do we need to stop this behaviour?

2017-04-13 06:09 UTC, markccchiang commented
If Grimmer has no other opinions, I think we can disable this behavior.

2017-04-13 14:00 GMT+08:00 Anthony Moraghan <notifications@github.com>:

> Thanks Mark. It seems to me that when we run "carta.sh", if
> ~/.cartavis/config.json is not present, then it will run setupcartavis.sh
> which will copy it there.
>
> /CARTAvis/carta/scripts/legacy/carta.sh:
>
> if [ ! -d $HOME/CARTA/Images/CubesTest -o\
>      ! -d $HOME/.cartavis/log  -o\
>      ! -f $HOME/.cartavis/config.json -o\
>      ! -d $HOME/CARTA/snapshots/data ]; then
>     $dirname/setupcartavis.sh 2>&1  > /dev/null
> fi
>
> /CARTAvis/carta/scripts/setupcartavis.sh
>
> # check that config.json exists
> if [ ! -f $HOME/.cartavis/config.json ]; then
>     echo "copying config.json file to  $HOME/.cartavis directory..."
>     cp $dirname/config/config.json $HOME/.cartavis
> fi
>
> Do we need to stop this behaviour?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CARTAvis/carta/pull/57#issuecomment-293790035>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AFIWEtTCdYsWhUr2oGvve30v4yZ6ocASks5rvbnlgaJpZM4M2XM8>
> .
>

2017-04-13 06:30 UTC, ajm-asiaa commented
It doesn't seem to work for me without config.json in the usual place.
```
Parsing global settings from "/Users/ajm/.cartavis/config.json"
Could not open main config file from "/Users/ajm/.cartavis/config.json"
```

So for you it reads config.json from /Contents/Resources/config/config.json ?

2017-04-13 06:50 UTC, markccchiang commented
It seems the current develop branch does not merge my previous pull
request:

https://github.com/CARTAvis/carta/pull/46/files

which can read the config.json from the default directory
carta/config/config.json. I will check with Grimmer.


2017-04-13 14:30 GMT+08:00 Anthony Moraghan <notifications@github.com>:

> It doesn't seem to work for me without config.json in the usual place.
>
> Parsing global settings from "/Users/ajm/.cartavis/config.json"
> Could not open main config file from "/Users/ajm/.cartavis/config.json"
>
> So for you it reads config.json from /Contents/Resources/config/config.json
> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CARTAvis/carta/pull/57#issuecomment-293797997>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AFIWErQ-Rm1Lf6VCJc8NWml6gpnbfrfBks5rvcDugaJpZM4M2XM8>
> .
>

2017-04-14 03:32 UTC, ajm-asiaa commented
Hi Mark. OK. I combined pull request 46 and 47 together. 
It is going back through too many directories after we package CARTA:

> Parsing global settings from "/private/tmp/Carta.app/Contents/MacOS/../../../../../config/config.json"
> Could not open main config file from "/private/tmp/Carta.app/Contents/MacOS/../../../../../config/config.json"

For Mac it would only need to go back one directory and then into 'Resources'. For example, it could be /Carta.app/Contents/Resources/config/config.json

So I propose to change Line62 of CmdLine.cpp to
```
 info.m_configFilePath = QCoreApplication::applicationDirPath() + "/../Resources/config/config.json";
```
I tried it and it works.

Similarly for the packaged Linux case, Line 60 of CmdLine.cpp should be
```
info.m_configFilePath = QCoreApplication::applicationDirPath() + "/../etc/config/config.json";
```

2017-04-17 04:56 UTC, ajm-ska requested changes
These changes should be made so that it will work once CARTA is packaged.

2017-04-17 04:56 UTC, ajm-asiaa commented on carta/cpp/core/CmdLine.cpp
> +        info.m_configFilePath = QCoreApplication::applicationDirPath() + "/../../../../../config/config.json";
info.m_configFilePath = QCoreApplication::applicationDirPath() + "/../Resources/config/config.json";

2017-04-17 04:56 UTC, ajm-asiaa commented on carta/cpp/core/CmdLine.cpp
> +        info.m_configFilePath = QCoreApplication::applicationDirPath() + "/../../config/config.json";
info.m_configFilePath = QCoreApplication::applicationDirPath() + "/../etc/config/config.json";

2017-04-17 06:56 UTC, markccchiang commented on carta/cpp/core/CmdLine.cpp
> +        info.m_configFilePath = QCoreApplication::applicationDirPath() + "/../../../../../config/config.json";
Thanks Anthony! I have made changes in `CmdLine.cpp`. Please check if it works in CARTA packaged program.

2017-04-17 07:02 UTC, markccchiang commented on carta/cpp/core/CmdLine.cpp
> +        info.m_configFilePath = QCoreApplication::applicationDirPath() + "/../../config/config.json";
Thanks Anthony! I have made changes in CmdLine.cpp. Please check if it works in CARTA packaged program.

2017-04-19 05:01 UTC, ajm-ska approved these changes

2017-04-19 05:06 UTC, ajm-asiaa commented
I checked on Mac and CentOS7 versions. This works fine.
 
I can just copy the config.json to the correct location in a packaging step.

Maybe next time when we are improving the carta.sh script, we can remove or comment out lines 38 to 42 of the setupcartavis.sh script in order to stop it copying config.json to ~/.cartavis/

`# check that config.json exists
if [ ! -f $HOME/.cartavis/config.json ]; then
	echo "copying config.json file to  $HOME/.cartavis directory..."
	cp $dirname/config/config.json $HOME/.cartavis
fi` 

Meanwhile, I can just comment out those lines when packaging.

2017-04-21 03:58 UTC, merged